name: Release Microsoft Marketplace

on:
  push:
    branches: [release/*]

jobs:
  publish-npm:
    name: Publish NPM module
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      # https://code.visualstudio.com/api/working-with-extensions/publishing-extension
      - name: Login
        run: echo "${{ secrets.MICROSOFT_MARKETPLACE_TOKEN }}" | ./node_modules/.bin/vsce login Cucumber
      - name: Publish
        run: ./node_modules/.bin/vsce publish
