name: Release GitHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cucumber/action-create-github-release@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ github.workspace }}
          files: |
            Release.txt
            LICENSE